### ISSUE TITLE
how to get an image stream from the cameras?

### ISSUE THREAD

**Issue by holygame** [robotology/icub-tutorials#12]
I'm trying to get an image stream from the icub/icubSim cameras to use it with the ovrheadset driver .
If my understanding is correct , the ports where the images are streamed are  /icub/cam/left  and /icub/cam/right. 
i'm stuck on how to actually get the cameras to send images on those ports. For example , when controlling the head  we open the "remote_controlboard" device and connect it to the appropriate ports. What device and what interfaces do we need open to stream the output of the cameras ( for both icub and icubSim ).

Thank you for your help.

**Comment by pattacini** [comment]
Hi @holygame 
Welcome in robotology.

The proper place where discussing topics and asking for assistance is our Q&A repo. Therefore, I'll redirect there your request.

**Comment by pattacini** [comment]
Issue moved to [robotology/QA #311](https://github.com/robotology/QA/issues/311) via [**ZenHub**](https://www.zenhub.com/)
