### ISSUE TITLE
Movement error when Iaunching tutorial_cartesian_interface on gazebo

### ISSUE THREAD

**Issue by DermyO** [robotology/icub-tutorials#8]
Hello!

when I launch the program tutorial_cartesian_interface on Gazebo, the simulated robot fall down.

Here are some information that could be usefull:

* I've updated my computer to ubuntu 16 and I passed from iCubGazeboSim to icubSim.  I think I have misunderstood the transition between icubGazeboSim to icubSim: I am not sure to understand where I have to keep "icubGazeboSim" or where I have to write "icubSim".
* I putted in the bashrc "YARP_ROBOT_NAME=icubGazeboSim" ;
* I tried to launch the program wether with --robot icubSim and robot icubGazeboSim.;
* I use :
``wholeBodyDynamicsTree --robot icubSim``
with files in [...]codyco-superbuild/build/install/share/codyco/robots/icubGazeboSim/[...]
(Not usefull there but I willl need it after, so I would like to verify if it is ok)
``yarprobotinterface --context simCartesianControl --robot icubSim``
with files in [..]/share/iCub/contexts/simCartesianControl/[...]
``iKinCartesianSolver --robot icubSim --context simCartesianControl --part left_arm``
with files in [..]/share/iCub/contexts/simCartesianControl/[...] and [...]/codyco-superbuild/build/install/share/codyco/robots/icubGazeboSim[...]

Thank you for your help!
@pattacini @arwen-h

**Comment by pattacini** [comment]
Hi @misaki43 

I believe the problem you're experiencing with Gazebo is very much related to https://github.com/robotology/icub-gazebo/issues/38.
